name: hello-world
on: push
jobs:
  GettingRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out the Repo
        uses: actions/checkout@v3
      - name: show repo folder content
        run: ls
      - name: Run Python Scripts
        run: python test.py