name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello World!"
      - name: Checking if Python exists
        run: python --version
      - name: Checking File Structure
        run: cat test.py
      # - name: Trying to run code
      #   run: python test.py
