name: hello-world
on: push
jobs:
  GettingRepo:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Checking Out the Repo
        uses: actions/checkout@v3
      - name: Running the Python Script
        uses: python test.py
      # - name: show repo folder content
      #   run: ls
      # - name: show file content
      #   run: cat test.py
